import AlgebraicTests.Core
import AlgebraicTests.Circuit
import AlgebraicTests.CircuitFamily
import AlgebraicTests.AC0
import AlgebraicTests.AC0DecisionTree
import AlgebraicTests.AC0Parity
import AlgebraicTests.AC0ParityCircuit
import AlgebraicTests.AC0Duality
import AlgebraicTests.AC0TreeNormalForm
import AlgebraicTests.AC0Layer
import AlgebraicTests.AC0LayerFormula
import AlgebraicTests.AC0LayerSwitching
import AlgebraicTests.AC0LayerExistence
import AlgebraicTests.AC0LayerIteration
import AlgebraicTests.AC0CanonicalDecisionTree
import AlgebraicTests.AC0NormalForm
import AlgebraicTests.AC0LiteralGate
import AlgebraicTests.AC0BottomGate
import AlgebraicTests.AC0BottomFamily
import AlgebraicTests.AC0RandomRestriction
import AlgebraicTests.AC0RestrictionAveraging
import AlgebraicTests.AC0SwitchingEncoding
import AlgebraicTests.AC0CombinedAdvice
import AlgebraicTests.AC0CanonicalEncoding
import AlgebraicTests.AC0CombinedCanonicalEncoding
import AlgebraicTests.AC0CombinedCanonicalTrace
import AlgebraicTests.AC0CombinedCanonicalPacking
import AlgebraicTests.AC0CanonicalSwitching
import AlgebraicTests.AC0CombinedCanonical
import AlgebraicTests.AC0Switching
import AlgebraicTests.AC0SwitchingFamily
import AlgebraicTests.PartialAssignment
import AlgebraicTests.Translation
import AlgebraicTests.LowerBounds
import AlgebraicTests.MassProduction

/-!
# Algebraic public API regression suite

This test driver compiles small downstream-style uses of the library's public
circuit, circuit-family, translation, and lower-bound interfaces.
-/
