name = "algebraic"
version = "0.1.0"
defaultTargets = ["Algebraic"]
testDriver = "AlgebraicTests"
lintDriver = "batteries/runLinter"
lintDriverArgs = ["Algebraic"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "950d27063f377d5ccd80d3eeedcebe319d3eb821"

[[require]]
name = "cslib"
git = "https://github.com/leanprover/cslib"
rev = "6c3d6fd806a72d5f575091f81eafd5cd7b92b4c3"

[[lean_lib]]
name = "Algebraic"

[[lean_lib]]
name = "AlgebraicTests"
