import Algebraic.LowerBound.Fusion.Boolean
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Fintype.Pi

/-!
# A fusion lower bound for the inequality graph

Let `N = 2 ^ n`.  View the inequality relation on `Fin N × Fin N` as a set
generated by its rows and columns.  The canonical semi-filter above an unequal
pair `(u, v)` accepts a subset of the diagonal when it contains `(u, u)` or
`(v, v)`.

Every pair in a fusion cover supplies one Boolean bit for each vertex: whether
its diagonal point belongs to the left member of the pair.  If two vertices
had the same complete code, their canonical semi-filter would preserve every
pair.  Consequently the code is injective, so `N ≤ 2 ^ cover.cost`.  At
`N = 2 ^ n` this gives a lower bound of `n` AND gates, even when OR gates are
free.  The matching construction from the literature is not formalized here.

This is the coding form of the canonical-semi-filter argument for the
inequality graph in Cavalar--Oliveira, Proposition 40.
-/

namespace Algebraic
namespace Fusion

/-- The upward-closed family of sets containing at least one of two points. -/
def Semifilter.twoPoint (left right : U) : Semifilter U where
  carrier := { set | left ∈ set ∨ right ∈ set }
  nonempty := ⟨Set.univ, by simp⟩
  upward := by
    intro lower upper present subset
    rcases present with leftPresent | rightPresent
    · exact Or.inl (subset leftPresent)
    · exact Or.inr (subset rightPresent)
  empty_not_mem := by simp

@[simp] theorem Semifilter.mem_twoPoint
    (left right : U)
    (set : Set U) :
    set ∈ Semifilter.twoPoint left right ↔
      left ∈ set ∨ right ∈ set := Iff.rfl

/-- If the left member of a pair does not distinguish two points, their
two-point semi-filter preserves the pair. -/
theorem Semifilter.twoPoint_preservesPair_of_left_iff
    (left right : U)
    (pair : Set U × Set U)
    (same : left ∈ pair.1 ↔ right ∈ pair.1) :
    (Semifilter.twoPoint left right).PreservesPair pair := by
  intro leftAccepted rightAccepted
  rw [Semifilter.mem_twoPoint] at leftAccepted rightAccepted ⊢
  have bothLeft : left ∈ pair.1 ∧ right ∈ pair.1 := by
    rcases leftAccepted with leftPresent | rightPresent
    · exact ⟨leftPresent, same.mp leftPresent⟩
    · exact ⟨same.mpr rightPresent, rightPresent⟩
  rcases rightAccepted with leftPresent | rightPresent
  · exact Or.inl ⟨bothLeft.1, leftPresent⟩
  · exact Or.inr ⟨bothLeft.2, rightPresent⟩

namespace Neq

/-- Ambient space for an `N` by `N` bipartite graph. -/
abbrev Ground (N : Nat) := Fin N × Fin N

/-- The star consisting of one row. -/
def row (vertex : Fin N) : Set (Ground N) :=
  { edge | edge.1 = vertex }

/-- The star consisting of one column. -/
def column (vertex : Fin N) : Set (Ground N) :=
  { edge | edge.2 = vertex }

/-- The bipartite inequality graph. -/
def target (N : Nat) : Set (Ground N) :=
  { edge | edge.1 ≠ edge.2 }

/-- Construct the inequality graph from all row and column stars. -/
abbrev problem (N : Nat) : SetProblem (Ground N) where
  inputCount := N + N
  inputs := Fin.addCases row column
  target := target N

@[simp] theorem problem_inputs_natAdd
    (vertex : Fin N) :
    (problem N).inputs (Fin.natAdd N vertex) = column vertex := by
  unfold problem
  change Fin.addCases (row (N := N)) (column (N := N))
    (Fin.natAdd N vertex) = column vertex
  exact Fin.addCases_right vertex

/-- A diagonal point, regarded as a point outside the inequality graph. -/
def diagonal (vertex : Fin N) : Problem.Outside (problem N) :=
  ⟨(vertex, vertex), by simp [target]⟩

@[simp] theorem diagonal_value (vertex : Fin N) :
    (diagonal vertex : Ground N) = (vertex, vertex) := rfl

/-- The canonical semi-filter associated with the unequal edge `(left, right)`. -/
abbrev canonicalFilter (left right : Fin N) :
    Semifilter (Problem.Outside (problem N)) :=
  Semifilter.twoPoint (diagonal left) (diagonal right)

/-- The canonical semi-filter is above its corresponding edge. -/
theorem canonicalFilter_above
    (left right : Fin N) :
    (canonicalFilter left right).Above
      (problem := problem N) (left, right) := by
  intro input
  refine Fin.addCases (motive := fun input =>
    (left, right) ∈ (problem N).inputs input →
      (problem N).restrict ((problem N).inputs input) ∈
        canonicalFilter left right) (fun rowVertex present => ?_)
      (fun columnVertex present => ?_) input
  · rw [Semifilter.mem_twoPoint]
    left
    rw [Problem.mem_restrict]
    simpa [row] using present
  · rw [Semifilter.mem_twoPoint]
    right
    rw [Problem.mem_restrict]
    rw [problem_inputs_natAdd]
    have present' : (left, right) ∈ column columnVertex := by
      change (left, right) ∈ Fin.addCases
        (motive := fun _ => Set (Ground N)) (row (N := N))
          (column (N := N)) (Fin.natAdd N columnVertex) at present
      rw [Fin.addCases_right] at present
      exact present
    simpa [column] using present'

noncomputable section

/-- Boolean membership code assigned to a vertex by a pair cover. -/
def coverCode
    (cover : PairCover (problem N) SemifilterClass.all)
    (vertex : Fin N) : Fin cover.pairs.length → Bool :=
  fun index => AndOr.membership (diagonal vertex)
    (cover.pairs.get index).1

/-- A cover of all semi-filters assigns distinct codes to distinct vertices. -/
theorem coverCode_injective
    (cover : PairCover (problem N) SemifilterClass.all) :
    Function.Injective (coverCode cover) := by
  classical
  intro left right codesEqual
  by_contra different
  have targetPresent : (left, right) ∈ (problem N).target := by
    simpa [target] using different
  have somePairFails := cover.isCover (left, right) targetPresent
    (canonicalFilter left right) (by trivial)
      (canonicalFilter_above left right)
  apply somePairFails
  intro pair pairPresent
  obtain ⟨index, pairAtIndex⟩ := (List.mem_iff_get.mp pairPresent)
  rw [← pairAtIndex]
  apply Semifilter.twoPoint_preservesPair_of_left_iff
  have bitEqual := congrFun codesEqual index
  exact (AndOr.membership_points_eq_iff
    (diagonal left) (diagonal right) _).mp bitEqual

/-- Information-theoretic form of the canonical semi-filter lower bound. -/
theorem card_le_two_pow_cost
    (cover : PairCover (problem N) SemifilterClass.all) :
    N ≤ 2 ^ cover.cost := by
  have cardinality := Fintype.card_le_of_injective
    (coverCode cover) (coverCode_injective cover)
  simpa [PairCover.cost] using cardinality

/-- Every pair cover of the `2 ^ n`-vertex inequality graph has at least `n`
pairs. -/
theorem pairCover_cost_lowerBound
    (cover : PairCover (problem (2 ^ n)) SemifilterClass.all) :
    n ≤ cover.cost := by
  apply (Nat.pow_le_pow_iff_right (by decide : 2 ≤ 2)).mp
  exact card_le_two_pow_cost cover

/-- The full semi-filter cover complexity of the inequality graph is at least
`n`. -/
theorem le_pairCoverComplexity (n : Nat) :
    (n : ℕ∞) ≤ pairCoverComplexity
      (problem (2 ^ n)) SemifilterClass.all := by
  unfold pairCoverComplexity
  apply le_iInf
  intro cover
  exact_mod_cast pairCover_cost_lowerBound cover

/-- Any row/column construction of the `2 ^ n`-vertex inequality graph uses
at least `n` AND gates, even with free OR gates. -/
theorem and_lowerBound
    (circuit : Circuit AndOr.signature
      ((2 ^ n) + (2 ^ n)) g 1)
    (constructs : (problem (2 ^ n)).Constructs circuit
      (AndOr.setInterpretation (Ground (2 ^ n)))) :
    n ≤ circuit.cost AndOr.andCost :=
  pairCover_lowerBound (problem (2 ^ n)) SemifilterClass.all
    pairCover_cost_lowerBound circuit constructs

end

end Neq
end Fusion
end Algebraic
